In [129]:
#write input states in code
#print out input states
#write percent chances/probabilities in code
# do not print percent chances
#roll d20 with random num generator

#print out measurement and score after every time

#final: print out state being guessed with correct or incorrect with probabilities

In [130]:
import random
random.seed()
import numpy as np

In [131]:
#write input states as matrix
#these are the psi given states
#rows are each psi
#columns are the constants in front of x, y, and z
#CHANGE FOR NEW INPUT STATES
inputstates=np.array([[0.612,-0.782,-0.118],
              [0.690,0.599,-0.408],
              [-0.706,-0.656,0.269],
              [-0.174,0.796,-0.580],
              [-0.577,-0.753,-0.315],
              [0.129,-0.967,0.220],
              [-0.221,0.588,0.778],
              [0.254,-0.340,-0.906]]) #this is the given input states with the values of x,y, and z CHANGE
Ninputstates=inputstates.shape[0]
print(inputstates)
#point system
dsize=20
maxguess=20
penalty=5

[[ 0.612 -0.782 -0.118]
 [ 0.69   0.599 -0.408]
 [-0.706 -0.656  0.269]
 [-0.174  0.796 -0.58 ]
 [-0.577 -0.753 -0.315]
 [ 0.129 -0.967  0.22 ]
 [-0.221  0.588  0.778]
 [ 0.254 -0.34  -0.906]]


In [132]:
#define x y and z measurements
measurements=np.array([[1.,0.,0.],
                     [0.,1.,0.],
                     [0.,0.,1.]]) #this defines what x y and z mean
Nmeasurements=measurements.shape[0]
#print(measurements)

In [133]:
#Build lookup table (probablility of measuring + for each state) [axis, states]
prob=np.zeros((measurements.shape[0],Ninputstates),dtype=int)
for i in range(measurements.shape[0]):
    for j in range(Ninputstates):
        prob[i, j] = (0.5*(1.0+np.dot(inputstates[j],measurements[i]))*dsize)
print (prob)
# rows are x, y, z and columns are states

[[16 16  2  8  4 11  7 12]
 [ 2 15  3 17  2  0 15  6]
 [ 8  5 12  4  6 12 17  0]]


In [134]:
def measure(inputstate, measurement):

    # Roll a dice with random number generator
    if (random.randint(1,dsize)<=prob[measurements,inputstates]):
        out = 1
    else:
        out = -1
    return out

In [153]:
#def chooserow(newValue):
max_value=0;
secondprob=0;
chooserow=prob[(random.randint(0,2)),:]
print (chooserow)

[ 8  5 12  4  6 12 17  0]


In [154]:
#def chooserow(newValue):
#max_value=0;
#secondprob=0;
#chooserow=prob[(random.randint(0,2)),:]
#print (chooserow)

#possible update for code, once guess is incorrect then we omit that from the code and the incorrect state's probability is zero

# tolerance=0.40
# tolerance comes in to effect after at least 4 measurements

out=-1
print (out)
#if (random.randint(1,dsize)<=chooserow[j]):
#    out = 1
#else:
#    out = -1
#    print (out)
if (out==1):
    newValue=chooserow/20
    print(newValue)
else:
    newValue=(1-(chooserow/20))
    print (newValue)
#    return newValue

-1
[0.6  0.75 0.4  0.8  0.7  0.4  0.15 1.  ]


In [137]:
firstguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #firstguess=(newValue*(1/8)/newValue.sum())
        firstguess=newValue*(1/8)
        firstguess=firstguess/firstguess.sum()
        print (firstguess)

[0.03333333 0.25       0.05       0.28333333 0.03333333 0.
 0.25       0.1       ]


In [140]:
secondguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #secondguess =(newValue*(firstguess))/(newValue*firstguess).sum()
        secondguess=newValue*firstguess
        secondguess=secondguess/secondguess.sum()
        print (secondguess)

[0.03463203 0.16233766 0.07792208 0.14718615 0.02597403 0.
 0.55194805 0.        ]


In [143]:
thirdguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #thirdguess =(newValue*(secondguess))/(newValue*secondguess).sum()
        thirdguess=newValue*secondguess
        thirdguess=thirdguess/thirdguess.sum()
        print (thirdguess)

[0.05295091 0.31025924 0.07942637 0.30005516 0.04633205 0.
 0.21097628 0.        ]


In [146]:
fourthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #fourthguess =(newValue*(thirdguess))/(newValue*thirdguess).sum()
        fourthguess=newValue*thirdguess
        fourthguess=fourthguess/fourthguess.sum()
        print (fourthguess)

[0.05291929 0.38759245 0.05291929 0.39983463 0.05402177 0.
 0.05271257 0.        ]


In [149]:
fifthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #fifthguess =(newValue*(fourthguess))/(newValue*fourthguess).sum()
        fifthguess=newValue*fourthguess
        fifthguess=fifthguess/fifthguess.sum()
        print (fifthguess)

[0.07279218 0.33321617 0.10918828 0.27499269 0.05573152 0.
 0.15407916 0.        ]


In [152]:
sixthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #sixthguess =(newValue*(fifthguess))/(newValue*fifthguess).sum()
        sixthguess=newValue*fifthguess
        sixthguess=sixthguess/sixthguess.sum()
        print (sixthguess)

[0.02975948 0.13622807 0.20087646 0.33727406 0.09113839 0.
 0.20472354 0.        ]


In [155]:
seventhguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #seventhguess =(newValue*(sixthguess))/(newValue*sixthguess).sum()
        seventhguess=newValue*sixthguess
        seventhguess=seventhguess/seventhguess.sum()
        print (seventhguess)

[0.03161966 0.18092916 0.14228848 0.47780822 0.11297442 0.
 0.05438007 0.        ]


In [128]:
eigthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #eigthguess =(newValue*(seventhguess))/(newValue*seventhguess).sum()
        eigthguess=newValue*seventhguess
        eigthguess=eigthguess/eigthguess.sum()
        print (eigthguess)

[0.00324803 0.47578501 0.0004853  0.33244896 0.00094734 0.
 0.05919435 0.12789101]


In [ ]:
ninthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        #ninthguess =(newValue*(eigthguess))/(newValue*eigthguess).sum()
        ninthguess=newValue*eigthguess
        ninthguess=ninthguess/ninthguess.sum()
        print (ninthguess)

In [ ]:
#NO

tenthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        tenthguess =(newValue*(ninthguess))/(newValue*ninthguess).sum()
        print (tenthguess)

In [ ]:
# The cells below are our group's first attempt at the guessing project. We tried automating too much and overcomplicated 
# the task at hand. It is left here to see the thought process. 

In [13]:
#Play the Game
def play(newValue,out,max_value):
    guess=0;
    max_value=0;
    secondprob=0;
    j=0;
    #firstprob=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
    #secondprob=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
    firstprob=np.empty((8, 8),dtype=float)
    secondprob=np.empty((8, 8),dtype=float)
    test = -1
    if (max_value<0.70):
    #randomly choosing x y or z and plus or minus based on probabilities
        #if (guess==0):
        chooserow=prob[(random.randint(0,2)),:]
        print (chooserow)

        if (random.randint(1,dsize)<=chooserow[j]):
            out = 1
        else:
            out = -1
            print (out)
        if (out==1):
            newValue=chooserow/20
            print(newValue)
        else:
            newValue=(1-(chooserow/20))
            print (newValue)
            #for i in range(measurements.shape[0]):
        for i in range(1):
            for j in range(1):
                #result = measure(goal,test)
                firstprob[i]=(newValue*(1/8)/newValue.sum())
                #firstprob[j] =(prob[i,:]*(1/8))/prob.sum()
                guess=guess+1
                print (firstprob[i])
                #result = measure(goal,test)
                print("Guess=",guess)
                #return firstprob[j]
            while (guess>0) and (guess<=20):
                chooserow=prob[(random.randint(0,2)),:]
                print (chooserow)

                if (random.randint(1,dsize)<=chooserow[j]):
                    out = 1
                else:
                    out = -1
                print (out)
                if (out==1):
                    newValue=chooserow/20
                    print(newValue)
                else:
                    newValue=(1-(chooserow/20))
                    print (newValue)
                #for i in range(measurements.shape[0]):
                for i in range(1):
                    for j in range(1):
                        secondprob[i] =(newValue*(firstprob[i]))/newValue.sum()
                        #secondprob[j] =(prob[i,:]*(firstprob[j]))/prob.sum()
                        print (secondprob[i])
                        #result = measure(goal,test)
                        guess=guess+1
                        print("Guess=",guess)
                        max_value = np.max(secondprob[i])
                        print (max_value)
                        #searchValue >= 0.7
                        #index = secondprob.index(searchValue)
                        #print(" The element", searchValue, " is found at: ", index)
                        #return secondprob[j]
            else:
                print("Exceeded measurement limit!  Guesses = {}".format(guess))
                break
    if (max_value>=0.70):
        print (secondprob[j])

In [14]:
play(newValue,out,max_value)

[ 8  5 12  4  6 12 17  0]
[0.4  0.25 0.6  0.2  0.3  0.6  0.85 0.  ]
[0.015625   0.00976562 0.0234375  0.0078125  0.01171875 0.0234375
 0.03320312 0.        ]
Guess= 1
[ 2 15  3 17  2  0 15  6]
-1
[0.9  0.25 0.85 0.15 0.9  1.   0.25 0.7 ]
[0.0028125  0.00048828 0.00398437 0.00023438 0.00210937 0.0046875
 0.00166016 0.        ]
Guess= 2
0.004687499999999999
[ 8  5 12  4  6 12 17  0]
-1
[0.6  0.75 0.4  0.8  0.7  0.4  0.15 1.  ]
[0.00195312 0.00152588 0.00195312 0.00130208 0.00170898 0.00195312
 0.0010376  0.        ]
Guess= 3
0.0019531249999999996
[ 2 15  3 17  2  0 15  6]
-1
[0.9  0.25 0.85 0.15 0.9  1.   0.25 0.7 ]
[0.0028125  0.00048828 0.00398437 0.00023438 0.00210937 0.0046875
 0.00166016 0.        ]
Guess= 4
0.004687499999999999
[16 16  2  8  4 11  7 12]
1
[0.8  0.8  0.1  0.4  0.2  0.55 0.35 0.6 ]
[0.00328947 0.00205592 0.00061678 0.00082237 0.00061678 0.00339227
 0.00305818 0.        ]
Guess= 5
0.0033922697368421054
[16 16  2  8  4 11  7 12]
1
[0.8  0.8  0.1  0.4  0.2  0.55 0.35 0.